name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "$HOME/.databricks/bin" >> $GITHUB_PATH

    - name: Verify Databricks CLI
      run: |
        databricks --version

    - name: Deploy to Dev
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        databricks bundle deploy \
          --host ${{ secrets.DATABRICKS_DEV_HOST }} \
          --token ${{ secrets.DATABRICKS_DEV_TOKEN }} \
          --var "warehouse_id=${{ secrets.DATABRICKS_DEV_WAREHOUSE_ID }}" \
          --var "catalog=analytics_dev" \
          --force-lock
