name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "$HOME/.databricks/bin" >> $GITHUB_PATH

    - name: Verify Databricks CLI
      run: |
        databricks --version

    - name: Deploy to Dev
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
      run: |
        databricks bundle deploy -t dev \
          --var "warehouse_id=${{ secrets.DATABRICKS_DEV_WAREHOUSE_ID }}" \
          --var "catalog=analytics_dev" \
          --force-lock
