name: Deploy to Prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "$HOME/.databricks/bin" >> $GITHUB_PATH

    - name: Verify Databricks CLI
      run: |
        databricks --version

    - name: Deploy to Prod
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}  # Fixed: proper spacing
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
      run: |
        databricks bundle deploy -t prod \
          --var "warehouse_id=${{ secrets.DATABRICKS_PROD_WAREHOUSE_ID }}" \
          --var "catalog=analytics_prod" \
          --force-lock