name: Deploy to Prod

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        pip install databricks-bundle-cli databricks-cli

    - name: Deploy to Prod
      run: |
        databricks bundle deploy \
          --host ${{ secrets.DATABRICKS_PROD_HOST }} \
          --token ${{ secrets.DATABRICKS_PROD_TOKEN }} \
          --var "warehouse_id=${{ secrets.DATABRICKS_PROD_WAREHOUSE_ID }}" \
          --var "catalog=analytics_prod" \
          --force-lock
